# Generated by Django 5.2.5 on 2025-08-12 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ComicData', '0005_comicgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComicGroupMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('comic_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ComicData.comicgroup')),
            ],
        ),
    ]
