# Generated by Django 5.2.5 on 2025-08-12 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comicgroupmessage',
            name='avatar',
            field=models.URLField(blank=True, null=True),
        ),
    ]
