# Generated by Django 5.2.5 on 2025-08-18 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Messages', '0003_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['created_at']},
        ),
    ]
