# Generated by Django 5.2.5 on 2025-08-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messages', '0004_alter_comments_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='sender',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='user_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
