# Generated by Django 5.2.5 on 2025-08-19 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Messages', '0005_alter_comments_sender_alter_comments_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
