# Generated by Django 5.2.5 on 2025-08-19 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Messages', '0007_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
