# Generated by Django 5.2.5 on 2025-08-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messages', '0009_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='related_msg',
            field=models.ManyToManyField(default=list, related_name='CommentMessages', to='Messages.comments'),
        ),
    ]
