# Generated by Django 5.2.5 on 2025-08-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messages', '0010_alter_comments_related_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='related_msg',
            field=models.ManyToManyField(blank=True, related_name='CommentMessages', to='Messages.comments'),
        ),
    ]
