# Generated by Django 5.2.5 on 2025-08-19 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Messages', '0011_alter_comments_related_msg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
