# Generated by Django 5.2.5 on 2025-08-19 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Messages', '0013_comments_inboxmessages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InboxMessages',
            new_name='InboxComments',
        ),
    ]
