# Generated by Django 5.2.5 on 2025-08-19 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messages', '0014_rename_inboxmessages_inboxcomments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboxcomments',
            name='ParentMsg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CommentsChild', to='Messages.comments'),
        ),
    ]
