# Generated by Django 5.2.5 on 2025-08-12 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComicData', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='genre',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
