# Generated by Django 5.2.5 on 2025-08-12 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComicData', '0002_comic_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
