# Generated by Django 5.2.5 on 2025-08-12 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComicData', '0003_comic_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('chapter_number', models.IntegerField()),
                ('Chapter_image', models.JSONField(blank=True, null=True)),
                ('comic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='ComicData.comic')),
            ],
            options={
                'ordering': ['chapter_number'],
            },
        ),
    ]
