# Generated by Django 5.2.5 on 2025-08-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComicData', '0004_chapter'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComicGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('avatar', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
